name: convert

on:
  push:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |-
          npm install -g md-to-pdf
          echo; echo "Generating PDF"
          md-to-pdf --launch-options '{ "args": ["--no-sandbox"] }' --as-html cv.md
          ls
      
      - uses: actions/upload-artifact@v4
        with:
          name: cv.html
          path: cv.html

          